name: Inspect Model

on:
  workflow_dispatch:
    inputs:
      model_id:
        description: Model ID
        required: false
        type: string
  schedule:
    - cron: '0 0 */3 * *' 

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publications-and-repositories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v3.5.3

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh
        
      - name: Set Python to 3.10
        run:
         conda install -y python=3.10

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge

      - name: Install dependencies
        run: |
            source activate
            git clone https://github.com/ersilia-os/ersilia.git
      
      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          cd ersilia
          python -m pip install -e .
          pip install .[test]

      - name: Run Inspection Script
        env:
          MODEL_ID: ${{ github.event.inputs.model_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          REPO_OWNER: "ersilia-os"
          REPO_NAME: "ersilia-maintenance"
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate ersilia
          chmod +x .github/scripts/inspect.sh
          .github/scripts/inspect.sh
